using System;

// Token: 0x0200038A RID: 906
public static class UberShaderKeywords
{
	// Token: 0x04001B8F RID: 7055
	public const string STEREO_INSTANCING_ON = "STEREO_INSTANCING_ON";

	// Token: 0x04001B90 RID: 7056
	public const string UNITY_SINGLE_PASS_STEREO = "UNITY_SINGLE_PASS_STEREO";

	// Token: 0x04001B91 RID: 7057
	public const string STEREO_MULTIVIEW_ON = "STEREO_MULTIVIEW_ON";

	// Token: 0x04001B92 RID: 7058
	public const string STEREO_CUBEMAP_RENDER_ON = "STEREO_CUBEMAP_RENDER_ON";

	// Token: 0x04001B93 RID: 7059
	public const string _GLOBAL_ZONE_LIQUID_TYPE__WATER = "_GLOBAL_ZONE_LIQUID_TYPE__WATER";

	// Token: 0x04001B94 RID: 7060
	public const string _GLOBAL_ZONE_LIQUID_TYPE__LAVA = "_GLOBAL_ZONE_LIQUID_TYPE__LAVA";

	// Token: 0x04001B95 RID: 7061
	public const string _ZONE_LIQUID_SHAPE__CYLINDER = "_ZONE_LIQUID_SHAPE__CYLINDER";

	// Token: 0x04001B96 RID: 7062
	public const string _USE_TEXTURE = "_USE_TEXTURE";

	// Token: 0x04001B97 RID: 7063
	public const string USE_TEXTURE__AS_MASK = "USE_TEXTURE__AS_MASK";

	// Token: 0x04001B98 RID: 7064
	public const string _USE_WEATHER_MAP = "_USE_WEATHER_MAP";

	// Token: 0x04001B99 RID: 7065
	public const string _ALPHA_DETAIL_MAP = "_ALPHA_DETAIL_MAP";

	// Token: 0x04001B9A RID: 7066
	public const string _WATER_EFFECT = "_WATER_EFFECT";

	// Token: 0x04001B9B RID: 7067
	public const string _HEIGHT_BASED_WATER_EFFECT = "_HEIGHT_BASED_WATER_EFFECT";

	// Token: 0x04001B9C RID: 7068
	public const string _ALPHATEST_ON = "_ALPHATEST_ON";

	// Token: 0x04001B9D RID: 7069
	public const string _MAINTEX_ROTATE = "_MAINTEX_ROTATE";

	// Token: 0x04001B9E RID: 7070
	public const string _UV_WAVE_WARP = "_UV_WAVE_WARP";

	// Token: 0x04001B9F RID: 7071
	public const string _LIQUID_VOLUME = "_LIQUID_VOLUME";

	// Token: 0x04001BA0 RID: 7072
	public const string _LIQUID_CONTAINER = "_LIQUID_CONTAINER";

	// Token: 0x04001BA1 RID: 7073
	public const string _EMISSION = "_EMISSION";

	// Token: 0x04001BA2 RID: 7074
	public const string _EMISSION_USE_UV_WAVE_WARP = "_EMISSION_USE_UV_WAVE_WARP";

	// Token: 0x04001BA3 RID: 7075
	public const string _USE_DEFORM_MAP = "_USE_DEFORM_MAP";

	// Token: 0x04001BA4 RID: 7076
	public const string _USE_DAY_NIGHT_LIGHTMAP = "_USE_DAY_NIGHT_LIGHTMAP";

	// Token: 0x04001BA5 RID: 7077
	public const string _USE_TEX_ARRAY_ATLAS = "_USE_TEX_ARRAY_ATLAS";

	// Token: 0x04001BA6 RID: 7078
	public const string _CRYSTAL_EFFECT = "_CRYSTAL_EFFECT";

	// Token: 0x04001BA7 RID: 7079
	public const string _EYECOMP = "_EYECOMP";

	// Token: 0x04001BA8 RID: 7080
	public const string _MOUTHCOMP = "_MOUTHCOMP";

	// Token: 0x04001BA9 RID: 7081
	public const string _ALPHA_BLUE_LIVE_ON = "_ALPHA_BLUE_LIVE_ON";

	// Token: 0x04001BAA RID: 7082
	public const string _GRID_EFFECT = "_GRID_EFFECT";

	// Token: 0x04001BAB RID: 7083
	public const string _REFLECTIONS = "_REFLECTIONS";

	// Token: 0x04001BAC RID: 7084
	public const string _REFLECTIONS_BOX_PROJECT = "_REFLECTIONS_BOX_PROJECT";

	// Token: 0x04001BAD RID: 7085
	public const string _REFLECTIONS_USE_NORMAL_TEX = "_REFLECTIONS_USE_NORMAL_TEX";

	// Token: 0x04001BAE RID: 7086
	public const string _VERTEX_ROTATE = "_VERTEX_ROTATE";

	// Token: 0x04001BAF RID: 7087
	public const string _VERTEX_ANIM_FLAP = "_VERTEX_ANIM_FLAP";

	// Token: 0x04001BB0 RID: 7088
	public const string _VERTEX_ANIM_WAVE = "_VERTEX_ANIM_WAVE";

	// Token: 0x04001BB1 RID: 7089
	public const string _VERTEX_ANIM_WAVE_DEBUG = "_VERTEX_ANIM_WAVE_DEBUG";

	// Token: 0x04001BB2 RID: 7090
	public const string _VERTEX_LIGHTING = "_VERTEX_LIGHTING";

	// Token: 0x04001BB3 RID: 7091
	public const string _GRADIENT_MAP_ON = "_GRADIENT_MAP_ON";

	// Token: 0x04001BB4 RID: 7092
	public const string _PARALLAX = "_PARALLAX";

	// Token: 0x04001BB5 RID: 7093
	public const string _PARALLAX_AA = "_PARALLAX_AA";

	// Token: 0x04001BB6 RID: 7094
	public const string _PARALLAX_PLANAR = "_PARALLAX_PLANAR";

	// Token: 0x04001BB7 RID: 7095
	public const string _MASK_MAP_ON = "_MASK_MAP_ON";

	// Token: 0x04001BB8 RID: 7096
	public const string _FX_LAVA_LAMP = "_FX_LAVA_LAMP";

	// Token: 0x04001BB9 RID: 7097
	public const string _INNER_GLOW = "_INNER_GLOW";

	// Token: 0x04001BBA RID: 7098
	public const string _STEALTH_EFFECT = "_STEALTH_EFFECT";

	// Token: 0x04001BBB RID: 7099
	public const string _UV_SHIFT = "_UV_SHIFT";

	// Token: 0x04001BBC RID: 7100
	public const string _TEXEL_SNAP_UVS = "_TEXEL_SNAP_UVS";

	// Token: 0x04001BBD RID: 7101
	public const string _UNITY_EDIT_MODE = "_UNITY_EDIT_MODE";

	// Token: 0x04001BBE RID: 7102
	public const string _GT_EDITOR_TIME = "_GT_EDITOR_TIME";

	// Token: 0x04001BBF RID: 7103
	public const string _DEBUG_PAWN_DATA = "_DEBUG_PAWN_DATA";

	// Token: 0x04001BC0 RID: 7104
	public const string _COLOR_GRADE_PROTANOMALY = "_COLOR_GRADE_PROTANOMALY";

	// Token: 0x04001BC1 RID: 7105
	public const string _COLOR_GRADE_PROTANOPIA = "_COLOR_GRADE_PROTANOPIA";

	// Token: 0x04001BC2 RID: 7106
	public const string _COLOR_GRADE_DEUTERANOMALY = "_COLOR_GRADE_DEUTERANOMALY";

	// Token: 0x04001BC3 RID: 7107
	public const string _COLOR_GRADE_DEUTERANOPIA = "_COLOR_GRADE_DEUTERANOPIA";

	// Token: 0x04001BC4 RID: 7108
	public const string _COLOR_GRADE_TRITANOMALY = "_COLOR_GRADE_TRITANOMALY";

	// Token: 0x04001BC5 RID: 7109
	public const string _COLOR_GRADE_TRITANOPIA = "_COLOR_GRADE_TRITANOPIA";

	// Token: 0x04001BC6 RID: 7110
	public const string _COLOR_GRADE_ACHROMATOMALY = "_COLOR_GRADE_ACHROMATOMALY";

	// Token: 0x04001BC7 RID: 7111
	public const string _COLOR_GRADE_ACHROMATOPSIA = "_COLOR_GRADE_ACHROMATOPSIA";

	// Token: 0x04001BC8 RID: 7112
	public const string LIGHTMAP_ON = "LIGHTMAP_ON";

	// Token: 0x04001BC9 RID: 7113
	public const string DIRLIGHTMAP_COMBINED = "DIRLIGHTMAP_COMBINED";

	// Token: 0x04001BCA RID: 7114
	public const string INSTANCING_ON = "INSTANCING_ON";

	// Token: 0x04001BCB RID: 7115
	public static readonly string[] namesArray = new string[]
	{
		"STEREO_INSTANCING_ON", "UNITY_SINGLE_PASS_STEREO", "STEREO_MULTIVIEW_ON", "STEREO_CUBEMAP_RENDER_ON", "_GLOBAL_ZONE_LIQUID_TYPE__WATER", "_GLOBAL_ZONE_LIQUID_TYPE__LAVA", "_ZONE_LIQUID_SHAPE__CYLINDER", "_USE_TEXTURE", "USE_TEXTURE__AS_MASK", "_USE_WEATHER_MAP",
		"_ALPHA_DETAIL_MAP", "_WATER_EFFECT", "_HEIGHT_BASED_WATER_EFFECT", "_ALPHATEST_ON", "_MAINTEX_ROTATE", "_UV_WAVE_WARP", "_LIQUID_VOLUME", "_LIQUID_CONTAINER", "_EMISSION", "_EMISSION_USE_UV_WAVE_WARP",
		"_USE_DEFORM_MAP", "_USE_DAY_NIGHT_LIGHTMAP", "_USE_TEX_ARRAY_ATLAS", "_CRYSTAL_EFFECT", "_EYECOMP", "_MOUTHCOMP", "_ALPHA_BLUE_LIVE_ON", "_GRID_EFFECT", "_REFLECTIONS", "_REFLECTIONS_BOX_PROJECT",
		"_REFLECTIONS_USE_NORMAL_TEX", "_VERTEX_ROTATE", "_VERTEX_ANIM_FLAP", "_VERTEX_ANIM_WAVE", "_VERTEX_ANIM_WAVE_DEBUG", "_VERTEX_LIGHTING", "_GRADIENT_MAP_ON", "_PARALLAX", "_PARALLAX_AA", "_PARALLAX_PLANAR",
		"_MASK_MAP_ON", "_FX_LAVA_LAMP", "_INNER_GLOW", "_STEALTH_EFFECT", "_UV_SHIFT", "_TEXEL_SNAP_UVS", "_UNITY_EDIT_MODE", "_GT_EDITOR_TIME", "_DEBUG_PAWN_DATA", "_COLOR_GRADE_PROTANOMALY",
		"_COLOR_GRADE_PROTANOPIA", "_COLOR_GRADE_DEUTERANOMALY", "_COLOR_GRADE_DEUTERANOPIA", "_COLOR_GRADE_TRITANOMALY", "_COLOR_GRADE_TRITANOPIA", "_COLOR_GRADE_ACHROMATOMALY", "_COLOR_GRADE_ACHROMATOPSIA", "LIGHTMAP_ON", "DIRLIGHTMAP_COMBINED", "INSTANCING_ON"
	};
}
